#!/usr/bin/env python3
\"\"\"
Common test fixtures and utilities

Generated by: Test Coverage Booster
\"\"\"

import pytest
from fastapi.testclient import TestClient
from app.main import app

@pytest.fixture
def client():
    \"\"\"Test client for API endpoints\"\"\"
    return TestClient(app)

@pytest.fixture
def sample_crypto_data():
    \"\"\"Sample cryptocurrency data for testing\"\"\"
    return {
        "bitcoin": {
            "price": 50000.0,
            "change": 5.2,
            "volume": 1000000
        },
        "ethereum": {
            "price": 3000.0,
            "change": -2.1,
            "volume": 500000
        }
    }

@pytest.fixture
def mock_user():
    \"\"\"Mock user for authentication tests\"\"\"
    return {
        "id": 1,
        "email": "test@example.com",
        "username": "testuser",
        "is_active": True
    }

@pytest.fixture
def auth_headers(mock_user):
    \"\"\"Authorization headers for authenticated requests\"\"\"
    # This would generate actual JWT token in real implementation
    return {"Authorization": "Bearer mock_token"}
