#!/usr/bin/env python3
"""
Common test fixtures and utilities

Generated by: Test Coverage Booster
"""

import os
from collections.abc import AsyncGenerator
from unittest.mock import AsyncMock, Mock

import pytest
import pytest_asyncio
from fastapi.testclient import TestClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.main import app


@pytest.fixture
def client():
    """Test client for API endpoints"""
    return TestClient(app)


@pytest.fixture
def mock_db_session():
    """Mock database session for service tests (sync version)"""
    session = AsyncMock()
    session.add = Mock()
    session.commit = AsyncMock()
    session.flush = AsyncMock()
    session.refresh = AsyncMock()
    session.rollback = AsyncMock()
    session.close = AsyncMock()
    session.execute = AsyncMock()
    return session


@pytest_asyncio.fixture
async def async_mock_db_session():
    """
    Mock database session for async tests (pytest 9.x compatible).

    Use this fixture for tests decorated with @pytest.mark.asyncio
    that need a mock database session.
    """
    session = AsyncMock()
    session.add = Mock()
    session.commit = AsyncMock()
    session.flush = AsyncMock()
    session.refresh = AsyncMock()
    session.rollback = AsyncMock()
    session.close = AsyncMock()
    session.execute = AsyncMock()
    yield session


@pytest.fixture
def sample_crypto_data():
    """Sample cryptocurrency data for testing"""
    return {
        "bitcoin": {"price": 50000.0, "change": 5.2, "volume": 1000000},
        "ethereum": {"price": 3000.0, "change": -2.1, "volume": 500000},
    }


@pytest.fixture
def mock_user():
    """Mock user for authentication tests"""
    return {
        "id": 1,
        "email": "test@example.com",
        "username": "testuser",
        "is_active": True,
    }


@pytest.fixture
def auth_headers(mock_user):
    """Authorization headers for authenticated requests"""
    # This would generate actual JWT token in real implementation
    return {"Authorization": "Bearer mock_token"}


@pytest.fixture
def sample_user_register_request():
    """Sample user registration request for testing"""
    from app.schemas.auth import UserRegisterRequest

    return UserRegisterRequest(
        email="newuser@example.com",
        password="SecurePass123!",
        full_name="New Test User",
        username="newuser",
    )


@pytest.fixture
def sample_user_login_request():
    """Sample user login request for testing"""
    from app.schemas.auth import UserLoginRequest

    return UserLoginRequest(email="test@example.com", password="TestPassword123!")


# ============================================================================
# INTEGRATION TEST FIXTURES (Session 33)
# ============================================================================


@pytest_asyncio.fixture(scope="function")
async def integration_db_session() -> AsyncGenerator[AsyncSession]:
    """
    Real database session for integration tests with transaction rollback.

    Purpose: Test database-dependent features that cannot be mocked:
    - SQLAlchemy server_default=func.now() timestamps
    - Database constraints (foreign keys, unique indexes)
    - Database-level pagination

    Pattern: Creates fresh tables, runs test, rolls back, drops tables

    Usage:
        @pytest.mark.asyncio
        @pytest.mark.integration
        async def test_with_database(integration_db_session):
            # Test code with real database
            pass
    """
    from app.core.database import Base  # Import Base from core

    # Get test database URL (defaults to main DATABASE_URL)
    test_db_url = os.getenv(
        "TEST_DATABASE_URL",
        os.getenv(
            "DATABASE_URL",
            "postgresql+asyncpg://lokifi:lokifi_dev_password@localhost:5432/lokifi_test",
        ),
    )

    # Create test engine
    test_engine = create_async_engine(
        test_db_url,
        echo=False,  # Disable SQL logging during tests
        pool_pre_ping=True,
    )

    # Try to connect to database - skip if unavailable
    try:
        async with test_engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
    except Exception as e:
        pytest.skip(f"Database unavailable for integration tests: {e}")

    # Create session maker
    TestSessionLocal = async_sessionmaker(
        test_engine,
        class_=AsyncSession,
        expire_on_commit=False,
    )

    # Create and yield session
    async with TestSessionLocal() as session:
        try:
            yield session
        finally:
            # Rollback any uncommitted changes
            await session.rollback()
            await session.close()

    # Drop all tables after test
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)

    # Dispose engine
    await test_engine.dispose()


@pytest.fixture
async def clear_cache():
    """Clear Redis cache before and after each test."""
    from app.core.redis_cache import clear_all_cache

    # Clear cache before test
    try:
        await clear_all_cache()
    except Exception:
        # Redis may not be available in all test environments
        pass

    yield

    # Clear cache after test
    try:
        await clear_all_cache()
    except Exception:
        pass
