name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Typecheck
        working-directory: frontend
        run: pnpm run typecheck || npx tsc -p tsconfig.json --noEmit

      - name: Tests
        working-directory: frontend
        run: pnpm run test || echo "No tests or vitest not configured"

      - name: Build
        working-directory: frontend
        run: pnpm run build
