version: '3.8'

services:
  backend:
    image: fynix/backend:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - fynix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: fynix/frontend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    networks:
      - fynix-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      replicas: 1
    volumes:
      - ./nginx_loadbalancer.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - fynix-network

networks:
  fynix-network:
    driver: overlay
    attachable: true