line-length = 100
target-version = "py311"
exclude = [
  ".venv",
  "__pycache__",
  "data",
]

[lint]
select = [
  "E",    # PEP 8 errors
  "F",    # Pyflakes
  "I",    # isort
  "UP",   # pyupgrade
  "S",    # flake8-bandit (security)
  "B",    # flake8-bugbear (likely bugs)
  "A",    # flake8-builtins (shadowing built-ins)
  "RUF",  # Ruff-specific rules
  "PERF", # Performance anti-patterns
]
ignore = [
  "E203",   # Whitespace before ':'
  "E266",   # Too many leading '#' for block comment
  "E501",   # Line too long (handled by formatter)
  "B008",   # Do not perform function call in defaults (FastAPI Depends pattern)
  "S101",   # Use of assert (allowed in tests)
  "S311",   # Non-cryptographic random (OK for non-security use)
  "S105",   # Possible hardcoded password (many false positives)
  "S106",   # Possible hardcoded password in argument
]

[lint.mccabe]
max-complexity = 10  # Flag complex functions
