/**
 * Common test utilities and helpers
 * 
 * Generated by: Test Coverage Booster
 */

import { render, RenderOptions } from '@testing-library/react'
import { ReactElement } from 'react'

// Mock crypto data for testing
export const mockCryptoData = {
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    price: 50000,
    change: 5.2,
    volume: 1000000
  },
  ethereum: {
    id: 'ethereum', 
    name: 'Ethereum',
    symbol: 'ETH',
    price: 3000,
    change: -2.1,
    volume: 500000
  }
}

// Mock user data
export const mockUser = {
  id: '1',
  email: 'test@example.com',
  username: 'testuser',
  isActive: true
}

// Custom render function with providers
export const customRender = (
  ui: ReactElement,
  options?: Omit<RenderOptions, 'wrapper'>
) => {
  return render(ui, {
    // Add providers here if needed (Theme, Router, etc.)
    ...options,
  })
}

// Re-export everything
export * from '@testing-library/react'
export { customRender as render }
