# Minimal Production Configuration
# Purpose: Lightweight production setup without database (uses external DB)
# Usage: docker compose -f docker-compose.prod-minimal.yml up
# Services: backend, frontend, redis (no postgres, no monitoring)
# Best for: Cloud deployments with managed databases

services:
  backend:
    build:
      context: ../../apps/backend
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ../../apps/backend/.env
    environment:
      # Override for production domains
      - FRONTEND_ORIGIN=https://your-domain.com
      - CORS_ORIGINS=["https://your-domain.com"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ../../apps/frontend
      target: prod
    working_dir: /app
    user: node
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.your-domain.com/api
      - NEXT_PUBLIC_API_BASE=https://api.your-domain.com
      - NODE_OPTIONS="--max_old_space_size=4096"
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
