"""
Test fixtures for profile

Auto-generated by Lokifi Fixture Generator
Provides realistic test data for models
"""

from datetime import UTC, datetime

import pytest

from app.schemas.profile import *

# ============================================================================
# ProfileUpdateRequest FIXTURES
# ============================================================================


@pytest.fixture
def sample_p_r_o_f_i_l_e_u_p_d_a_t_e_r_e_q_u_e_s_t():
    """Sample ProfileUpdateRequest for testing"""
    # TODO: Customize with realistic test data
    return ProfileUpdateRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_p_r_o_f_i_l_e_u_p_d_a_t_e_r_e_q_u_e_s_t_list():
    """List of sample ProfileUpdateRequests"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_p_r_o_f_i_l_e_u_p_d_a_t_e_r_e_q_u_e_s_t_factory():
    """Factory function for creating ProfileUpdateRequests with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ProfileUpdateRequest(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# UserSettingsUpdateRequest FIXTURES
# ============================================================================


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_u_p_d_a_t_e_r_e_q_u_e_s_t():
    """Sample UserSettingsUpdateRequest for testing"""
    # TODO: Customize with realistic test data
    return UserSettingsUpdateRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_u_p_d_a_t_e_r_e_q_u_e_s_t_list():
    """List of sample UserSettingsUpdateRequests"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_u_p_d_a_t_e_r_e_q_u_e_s_t_factory():
    """Factory function for creating UserSettingsUpdateRequests with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserSettingsUpdateRequest(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# NotificationPreferencesUpdateRequest FIXTURES
# ============================================================================


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_u_p_d_a_t_e_r_e_q_u_e_s_t():
    """Sample NotificationPreferencesUpdateRequest for testing"""
    # TODO: Customize with realistic test data
    return NotificationPreferencesUpdateRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_u_p_d_a_t_e_r_e_q_u_e_s_t_list():
    """List of sample NotificationPreferencesUpdateRequests"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_u_p_d_a_t_e_r_e_q_u_e_s_t_factory():
    """Factory function for creating NotificationPreferencesUpdateRequests with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return NotificationPreferencesUpdateRequest(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# ProfileResponse FIXTURES
# ============================================================================


@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e():
    """Sample ProfileResponse for testing"""
    # TODO: Customize with realistic test data
    return ProfileResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_list():
    """List of sample ProfileResponses"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_factory():
    """Factory function for creating ProfileResponses with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ProfileResponse(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# UserSettingsResponse FIXTURES
# ============================================================================


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_r_e_s_p_o_n_s_e():
    """Sample UserSettingsResponse for testing"""
    # TODO: Customize with realistic test data
    return UserSettingsResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_r_e_s_p_o_n_s_e_list():
    """List of sample UserSettingsResponses"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_s_e_t_t_i_n_g_s_r_e_s_p_o_n_s_e_factory():
    """Factory function for creating UserSettingsResponses with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserSettingsResponse(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# NotificationPreferencesResponse FIXTURES
# ============================================================================


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_r_e_s_p_o_n_s_e():
    """Sample NotificationPreferencesResponse for testing"""
    # TODO: Customize with realistic test data
    return NotificationPreferencesResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_r_e_s_p_o_n_s_e_list():
    """List of sample NotificationPreferencesResponses"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_n_o_t_i_f_i_c_a_t_i_o_n_p_r_e_f_e_r_e_n_c_e_s_r_e_s_p_o_n_s_e_factory():
    """Factory function for creating NotificationPreferencesResponses with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return NotificationPreferencesResponse(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# PublicProfileResponse FIXTURES
# ============================================================================


@pytest.fixture
def sample_p_u_b_l_i_c_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e():
    """Sample PublicProfileResponse for testing"""
    # TODO: Customize with realistic test data
    return PublicProfileResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_p_u_b_l_i_c_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_list():
    """List of sample PublicProfileResponses"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_p_u_b_l_i_c_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_factory():
    """Factory function for creating PublicProfileResponses with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return PublicProfileResponse(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# ProfileSearchResponse FIXTURES
# ============================================================================


@pytest.fixture
def sample_p_r_o_f_i_l_e_s_e_a_r_c_h_r_e_s_p_o_n_s_e():
    """Sample ProfileSearchResponse for testing"""
    # TODO: Customize with realistic test data
    return ProfileSearchResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_p_r_o_f_i_l_e_s_e_a_r_c_h_r_e_s_p_o_n_s_e_list():
    """List of sample ProfileSearchResponses"""
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_p_r_o_f_i_l_e_s_e_a_r_c_h_r_e_s_p_o_n_s_e_factory():
    """Factory function for creating ProfileSearchResponses with custom values"""

    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ProfileSearchResponse(**{**defaults, **kwargs})

    return _factory


# ============================================================================
# HELPER FIXTURES
# ============================================================================


@pytest.fixture
def mock_datetime():
    """Fixed datetime for testing"""
    return datetime(2025, 1, 1, 12, 0, 0, tzinfo=UTC)


@pytest.fixture
def sample_ids():
    """Sample IDs for testing"""
    return {"user": 1, "portfolio": 100, "asset": 1000, "alert": 10000}
