"""
Test fixtures for auth

Auto-generated by Lokifi Fixture Generator
Provides realistic test data for models
"""
from datetime import UTC, datetime

import pytest

from app.schemas.auth import *

# ============================================================================
# UserRegisterRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_u_s_e_r_r_e_g_i_s_t_e_r_r_e_q_u_e_s_t():
    """ Sample UserRegisterRequest for testing """
    # TODO: Customize with realistic test data
    return UserRegisterRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_r_e_g_i_s_t_e_r_r_e_q_u_e_s_t_list():
    """ List of sample UserRegisterRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_r_e_g_i_s_t_e_r_r_e_q_u_e_s_t_factory():
    """ Factory function for creating UserRegisterRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserRegisterRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# UserLoginRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_u_s_e_r_l_o_g_i_n_r_e_q_u_e_s_t():
    """ Sample UserLoginRequest for testing """
    # TODO: Customize with realistic test data
    return UserLoginRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_l_o_g_i_n_r_e_q_u_e_s_t_list():
    """ List of sample UserLoginRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_l_o_g_i_n_r_e_q_u_e_s_t_factory():
    """ Factory function for creating UserLoginRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserLoginRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# GoogleOAuthRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_g_o_o_g_l_e_o_a_u_t_h_r_e_q_u_e_s_t():
    """ Sample GoogleOAuthRequest for testing """
    # TODO: Customize with realistic test data
    return GoogleOAuthRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_g_o_o_g_l_e_o_a_u_t_h_r_e_q_u_e_s_t_list():
    """ List of sample GoogleOAuthRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_g_o_o_g_l_e_o_a_u_t_h_r_e_q_u_e_s_t_factory():
    """ Factory function for creating GoogleOAuthRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return GoogleOAuthRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# RefreshTokenRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_r_e_f_r_e_s_h_t_o_k_e_n_r_e_q_u_e_s_t():
    """ Sample RefreshTokenRequest for testing """
    # TODO: Customize with realistic test data
    return RefreshTokenRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_r_e_f_r_e_s_h_t_o_k_e_n_r_e_q_u_e_s_t_list():
    """ List of sample RefreshTokenRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_r_e_f_r_e_s_h_t_o_k_e_n_r_e_q_u_e_s_t_factory():
    """ Factory function for creating RefreshTokenRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return RefreshTokenRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# TokenResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_t_o_k_e_n_r_e_s_p_o_n_s_e():
    """ Sample TokenResponse for testing """
    # TODO: Customize with realistic test data
    return TokenResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_t_o_k_e_n_r_e_s_p_o_n_s_e_list():
    """ List of sample TokenResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_t_o_k_e_n_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating TokenResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return TokenResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# UserResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_u_s_e_r_r_e_s_p_o_n_s_e():
    """ Sample UserResponse for testing """
    # TODO: Customize with realistic test data
    return UserResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_r_e_s_p_o_n_s_e_list():
    """ List of sample UserResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating UserResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# ProfileResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e():
    """ Sample ProfileResponse for testing """
    # TODO: Customize with realistic test data
    return ProfileResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_list():
    """ List of sample ProfileResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_p_r_o_f_i_l_e_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating ProfileResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ProfileResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# AuthUserResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_a_u_t_h_u_s_e_r_r_e_s_p_o_n_s_e():
    """ Sample AuthUserResponse for testing """
    # TODO: Customize with realistic test data
    return AuthUserResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_a_u_t_h_u_s_e_r_r_e_s_p_o_n_s_e_list():
    """ List of sample AuthUserResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_a_u_t_h_u_s_e_r_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating AuthUserResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return AuthUserResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# MessageResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e():
    """ Sample MessageResponse for testing """
    # TODO: Customize with realistic test data
    return MessageResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e_list():
    """ List of sample MessageResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating MessageResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MessageResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# HELPER FIXTURES
# ============================================================================

@pytest.fixture
def mock_datetime():
    """ Fixed datetime for testing """
    return datetime(2025, 1, 1, 12, 0, 0, tzinfo=UTC)


@pytest.fixture
def sample_ids():
    """ Sample IDs for testing """
    return {
        'user': 1,
        'portfolio': 100,
        'asset': 1000,
        'alert': 10000
    }

