"""
Test fixtures for conversation

Auto-generated by Lokifi Fixture Generator
Provides realistic test data for models
"""
import pytest
from datetime import datetime, timezone
from typing import Any, Dict, List
from app.schemas.conversation import *

# ============================================================================
# MessageCreate FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_e_s_s_a_g_e_c_r_e_a_t_e():
    """ Sample MessageCreate for testing """
    # TODO: Customize with realistic test data
    return MessageCreate(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_e_s_s_a_g_e_c_r_e_a_t_e_list():
    """ List of sample MessageCreates """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_e_s_s_a_g_e_c_r_e_a_t_e_factory():
    """ Factory function for creating MessageCreates with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MessageCreate(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# MessageResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e():
    """ Sample MessageResponse for testing """
    # TODO: Customize with realistic test data
    return MessageResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e_list():
    """ List of sample MessageResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating MessageResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MessageResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# ConversationParticipantResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_p_a_r_t_i_c_i_p_a_n_t_r_e_s_p_o_n_s_e():
    """ Sample ConversationParticipantResponse for testing """
    # TODO: Customize with realistic test data
    return ConversationParticipantResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_p_a_r_t_i_c_i_p_a_n_t_r_e_s_p_o_n_s_e_list():
    """ List of sample ConversationParticipantResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_p_a_r_t_i_c_i_p_a_n_t_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating ConversationParticipantResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ConversationParticipantResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# ConversationResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_r_e_s_p_o_n_s_e():
    """ Sample ConversationResponse for testing """
    # TODO: Customize with realistic test data
    return ConversationResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_r_e_s_p_o_n_s_e_list():
    """ List of sample ConversationResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating ConversationResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ConversationResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# ConversationListResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_l_i_s_t_r_e_s_p_o_n_s_e():
    """ Sample ConversationListResponse for testing """
    # TODO: Customize with realistic test data
    return ConversationListResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_l_i_s_t_r_e_s_p_o_n_s_e_list():
    """ List of sample ConversationListResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_l_i_s_t_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating ConversationListResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ConversationListResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# MessagesListResponse FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_e_s_s_a_g_e_s_l_i_s_t_r_e_s_p_o_n_s_e():
    """ Sample MessagesListResponse for testing """
    # TODO: Customize with realistic test data
    return MessagesListResponse(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_e_s_s_a_g_e_s_l_i_s_t_r_e_s_p_o_n_s_e_list():
    """ List of sample MessagesListResponses """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_e_s_s_a_g_e_s_l_i_s_t_r_e_s_p_o_n_s_e_factory():
    """ Factory function for creating MessagesListResponses with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MessagesListResponse(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# ConversationCreateRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_c_r_e_a_t_e_r_e_q_u_e_s_t():
    """ Sample ConversationCreateRequest for testing """
    # TODO: Customize with realistic test data
    return ConversationCreateRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_c_r_e_a_t_e_r_e_q_u_e_s_t_list():
    """ List of sample ConversationCreateRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_c_o_n_v_e_r_s_a_t_i_o_n_c_r_e_a_t_e_r_e_q_u_e_s_t_factory():
    """ Factory function for creating ConversationCreateRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return ConversationCreateRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# MarkReadRequest FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_a_r_k_r_e_a_d_r_e_q_u_e_s_t():
    """ Sample MarkReadRequest for testing """
    # TODO: Customize with realistic test data
    return MarkReadRequest(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_a_r_k_r_e_a_d_r_e_q_u_e_s_t_list():
    """ List of sample MarkReadRequests """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_a_r_k_r_e_a_d_r_e_q_u_e_s_t_factory():
    """ Factory function for creating MarkReadRequests with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MarkReadRequest(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# TypingIndicatorMessage FIXTURES
# ============================================================================

@pytest.fixture
def sample_t_y_p_i_n_g_i_n_d_i_c_a_t_o_r_m_e_s_s_a_g_e():
    """ Sample TypingIndicatorMessage for testing """
    # TODO: Customize with realistic test data
    return TypingIndicatorMessage(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_t_y_p_i_n_g_i_n_d_i_c_a_t_o_r_m_e_s_s_a_g_e_list():
    """ List of sample TypingIndicatorMessages """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_t_y_p_i_n_g_i_n_d_i_c_a_t_o_r_m_e_s_s_a_g_e_factory():
    """ Factory function for creating TypingIndicatorMessages with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return TypingIndicatorMessage(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# NewMessageNotification FIXTURES
# ============================================================================

@pytest.fixture
def sample_n_e_w_m_e_s_s_a_g_e_n_o_t_i_f_i_c_a_t_i_o_n():
    """ Sample NewMessageNotification for testing """
    # TODO: Customize with realistic test data
    return NewMessageNotification(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_n_e_w_m_e_s_s_a_g_e_n_o_t_i_f_i_c_a_t_i_o_n_list():
    """ List of sample NewMessageNotifications """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_n_e_w_m_e_s_s_a_g_e_n_o_t_i_f_i_c_a_t_i_o_n_factory():
    """ Factory function for creating NewMessageNotifications with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return NewMessageNotification(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# MessageReadNotification FIXTURES
# ============================================================================

@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_a_d_n_o_t_i_f_i_c_a_t_i_o_n():
    """ Sample MessageReadNotification for testing """
    # TODO: Customize with realistic test data
    return MessageReadNotification(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_a_d_n_o_t_i_f_i_c_a_t_i_o_n_list():
    """ List of sample MessageReadNotifications """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_m_e_s_s_a_g_e_r_e_a_d_n_o_t_i_f_i_c_a_t_i_o_n_factory():
    """ Factory function for creating MessageReadNotifications with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return MessageReadNotification(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# WebSocketMessage FIXTURES
# ============================================================================

@pytest.fixture
def sample_w_e_b_s_o_c_k_e_t_m_e_s_s_a_g_e():
    """ Sample WebSocketMessage for testing """
    # TODO: Customize with realistic test data
    return WebSocketMessage(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_w_e_b_s_o_c_k_e_t_m_e_s_s_a_g_e_list():
    """ List of sample WebSocketMessages """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_w_e_b_s_o_c_k_e_t_m_e_s_s_a_g_e_factory():
    """ Factory function for creating WebSocketMessages with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return WebSocketMessage(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# RateLimitError FIXTURES
# ============================================================================

@pytest.fixture
def sample_r_a_t_e_l_i_m_i_t_e_r_r_o_r():
    """ Sample RateLimitError for testing """
    # TODO: Customize with realistic test data
    return RateLimitError(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_r_a_t_e_l_i_m_i_t_e_r_r_o_r_list():
    """ List of sample RateLimitErrors """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_r_a_t_e_l_i_m_i_t_e_r_r_o_r_factory():
    """ Factory function for creating RateLimitErrors with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return RateLimitError(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# UserStatus FIXTURES
# ============================================================================

@pytest.fixture
def sample_u_s_e_r_s_t_a_t_u_s():
    """ Sample UserStatus for testing """
    # TODO: Customize with realistic test data
    return UserStatus(
        # Add field values here
        # Example: id=1, name="test", created_at=datetime.now(timezone.utc)
    )


@pytest.fixture
def sample_u_s_e_r_s_t_a_t_u_s_list():
    """ List of sample UserStatuss """
    return [
        # TODO: Add multiple instances
    ]


@pytest.fixture
def sample_u_s_e_r_s_t_a_t_u_s_factory():
    """ Factory function for creating UserStatuss with custom values """
    def _factory(**kwargs):
        defaults = {
            # TODO: Add default values
        }
        return UserStatus(**{**defaults, **kwargs})
    return _factory

# ============================================================================
# HELPER FIXTURES
# ============================================================================

@pytest.fixture
def mock_datetime():
    """ Fixed datetime for testing """
    return datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc)


@pytest.fixture
def sample_ids():
    """ Sample IDs for testing """
    return {
        'user': 1,
        'portfolio': 100,
        'asset': 1000,
        'alert': 10000
    }

