version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: lokifi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass 23233 --appendonly yes
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=23233
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "23233", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - lokifi-network

volumes:
  redis-data:
    driver: local

networks:
  lokifi-network:
    driver: bridge
