// Top 270 Cryptocurrencies by Market Cap
// Generated: 2025-10-05T01:31:43.820Z
// Source: CoinGecko API

const top270Cryptos = [
  { symbol: 'BTC', name: 'Bitcoin', id: 'bitcoin', type: 'crypto', marketCap: 2436383707427 },
  { symbol: 'ETH', name: 'Ethereum', id: 'ethereum', type: 'crypto', marketCap: 540545496094 },
  { symbol: 'XRP', name: 'XRP', id: 'ripple', type: 'crypto', marketCap: 177377269871 },
  { symbol: 'USDT', name: 'Tether', id: 'tether', type: 'crypto', marketCap: 177094980313 },
  { symbol: 'BNB', name: 'BNB', id: 'binancecoin', type: 'crypto', marketCap: 159397443522 },
  { symbol: 'SOL', name: 'Solana', id: 'solana', type: 'crypto', marketCap: 123772998470 },
  { symbol: 'USDC', name: 'USDC', id: 'usd-coin', type: 'crypto', marketCap: 75340753093 },
  { symbol: 'STETH', name: 'Lido Staked Ether', id: 'staked-ether', type: 'crypto', marketCap: 38140912848 },
  { symbol: 'DOGE', name: 'Dogecoin', id: 'dogecoin', type: 'crypto', marketCap: 37905628965 },
  { symbol: 'TRX', name: 'TRON', id: 'tron', type: 'crypto', marketCap: 32252164081 },
  { symbol: 'ADA', name: 'Cardano', id: 'cardano', type: 'crypto', marketCap: 30591503398 },
  { symbol: 'WSTETH', name: 'Wrapped stETH', id: 'wrapped-steth', type: 'crypto', marketCap: 17616897551 },
  { symbol: 'WBETH', name: 'Wrapped Beacon ETH', id: 'wrapped-beacon-eth', type: 'crypto', marketCap: 15767906100 },
  { symbol: 'WBTC', name: 'Wrapped Bitcoin', id: 'wrapped-bitcoin', type: 'crypto', marketCap: 15505551490 },
  { symbol: 'LINK', name: 'Chainlink', id: 'chainlink', type: 'crypto', marketCap: 14940012020 },
  { symbol: 'USDE', name: 'Ethena USDe', id: 'ethena-usde', type: 'crypto', marketCap: 14827715674 },
  { symbol: 'HYPE', name: 'Hyperliquid', id: 'hyperliquid', type: 'crypto', marketCap: 13255775713 },
  { symbol: 'SUI', name: 'Sui', id: 'sui', type: 'crypto', marketCap: 12998478948 },
  { symbol: 'FIGR_HELOC', name: 'Figure Heloc', id: 'figure-heloc', type: 'crypto', marketCap: 12834008819 },
  { symbol: 'AVAX', name: 'Avalanche', id: 'avalanche-2', type: 'crypto', marketCap: 12619976354 },
  { symbol: 'XLM', name: 'Stellar', id: 'stellar', type: 'crypto', marketCap: 12561064160 },
  { symbol: 'WEETH', name: 'Wrapped eETH', id: 'wrapped-eeth', type: 'crypto', marketCap: 11872970362 },
  { symbol: 'BCH', name: 'Bitcoin Cash', id: 'bitcoin-cash', type: 'crypto', marketCap: 11731222295 },
  { symbol: 'WETH', name: 'WETH', id: 'weth', type: 'crypto', marketCap: 10913157054 },
  { symbol: 'LTC', name: 'Litecoin', id: 'litecoin', type: 'crypto', marketCap: 9283425592 },
  { symbol: 'HBAR', name: 'Hedera', id: 'hedera-hashgraph', type: 'crypto', marketCap: 9183257708 },
  { symbol: 'LEO', name: 'LEO Token', id: 'leo-token', type: 'crypto', marketCap: 8878487190 },
  { symbol: 'BSC-USD', name: 'Binance Bridged USDT (BNB Smart Chain)', id: 'binance-bridged-usdt-bnb-smart-chain', type: 'crypto', marketCap: 7989464964 },
  { symbol: 'USDS', name: 'USDS', id: 'usds', type: 'crypto', marketCap: 7957153041 },
  { symbol: 'CBBTC', name: 'Coinbase Wrapped BTC', id: 'coinbase-wrapped-btc', type: 'crypto', marketCap: 7910245911 },
  { symbol: 'SHIB', name: 'Shiba Inu', id: 'shiba-inu', type: 'crypto', marketCap: 7262335346 },
  { symbol: 'CRO', name: 'Cronos', id: 'crypto-com-chain', type: 'crypto', marketCap: 7138858341 },
  { symbol: 'TON', name: 'Toncoin', id: 'the-open-network', type: 'crypto', marketCap: 7054275047 },
  { symbol: 'USDT0', name: 'USDT0', id: 'usdt0', type: 'crypto', marketCap: 6674656722 },
  { symbol: 'DOT', name: 'Polkadot', id: 'polkadot', type: 'crypto', marketCap: 6372057799 },
  { symbol: 'MNT', name: 'Mantle', id: 'mantle', type: 'crypto', marketCap: 6371350524 },
  { symbol: 'WBT', name: 'WhiteBIT Coin', id: 'whitebit', type: 'crypto', marketCap: 6368198265 },
  { symbol: 'XMR', name: 'Monero', id: 'monero', type: 'crypto', marketCap: 6073192571 },
  { symbol: 'SUSDE', name: 'Ethena Staked USDe', id: 'ethena-staked-usde', type: 'crypto', marketCap: 5813350114 },
  { symbol: 'WLFI', name: 'World Liberty Financial', id: 'world-liberty-financial', type: 'crypto', marketCap: 5472466051 },
  { symbol: 'UNI', name: 'Uniswap', id: 'uniswap', type: 'crypto', marketCap: 4793907795 },
  { symbol: 'OKB', name: 'OKB', id: 'okb', type: 'crypto', marketCap: 4781219728 },
  { symbol: 'DAI', name: 'Dai', id: 'dai', type: 'crypto', marketCap: 4546805247 },
  { symbol: 'AAVE', name: 'Aave', id: 'aave', type: 'crypto', marketCap: 4297250527 },
  { symbol: 'ENA', name: 'Ethena', id: 'ethena', type: 'crypto', marketCap: 4199988691 },
  { symbol: 'PEPE', name: 'Pepe', id: 'pepe', type: 'crypto', marketCap: 4090957433 },
  { symbol: 'BGB', name: 'Bitget Token', id: 'bitget-token', type: 'crypto', marketCap: 3838414139 },
  { symbol: 'APT', name: 'Aptos', id: 'aptos', type: 'crypto', marketCap: 3686789630 },
  { symbol: 'NEAR', name: 'NEAR Protocol', id: 'near', type: 'crypto', marketCap: 3678842080 },
  { symbol: 'M', name: 'MemeCore', id: 'memecore', type: 'crypto', marketCap: 3538340596 },
  { symbol: 'JITOSOL', name: 'Jito Staked SOL', id: 'jito-staked-sol', type: 'crypto', marketCap: 3470090453 },
  { symbol: 'ASTER', name: 'Aster', id: 'aster-2', type: 'crypto', marketCap: 3169159247 },
  { symbol: 'TAO', name: 'Bittensor', id: 'bittensor', type: 'crypto', marketCap: 3040674970 },
  { symbol: 'IP', name: 'Story', id: 'story-2', type: 'crypto', marketCap: 3026578275 },
  { symbol: 'ETC', name: 'Ethereum Classic', id: 'ethereum-classic', type: 'crypto', marketCap: 2983685627 },
  { symbol: 'ONDO', name: 'Ondo', id: 'ondo-finance', type: 'crypto', marketCap: 2899167167 },
  { symbol: 'BUIDL', name: 'BlackRock USD Institutional Digital Liquidity Fund', id: 'blackrock-usd-institutional-digital-liquidity-fund', type: 'crypto', marketCap: 2829765385 },
  { symbol: 'BNSOL', name: 'Binance Staked SOL', id: 'binance-staked-sol', type: 'crypto', marketCap: 2786178239 },
  { symbol: 'WLD', name: 'Worldcoin', id: 'worldcoin-wld', type: 'crypto', marketCap: 2719893526 },
  { symbol: 'WETH', name: 'Binance-Peg WETH', id: 'binance-peg-weth', type: 'crypto', marketCap: 2708880436 },
  { symbol: 'ZEC', name: 'Zcash', id: 'zcash', type: 'crypto', marketCap: 2690077783 },
  { symbol: 'USD1', name: 'USD1', id: 'usd1-wlfi', type: 'crypto', marketCap: 2682877745 },
  { symbol: 'C1USD', name: 'Currency One USD', id: 'c1usd', type: 'crypto', marketCap: 2553291045 },
  { symbol: 'PYUSD', name: 'PayPal USD', id: 'paypal-usd', type: 'crypto', marketCap: 2544669855 },
  { symbol: 'POL', name: 'POL (ex-MATIC)', id: 'polygon-ecosystem-token', type: 'crypto', marketCap: 2490787085 },
  { symbol: 'ICP', name: 'Internet Computer', id: 'internet-computer', type: 'crypto', marketCap: 2412075951 },
  { symbol: 'JLP', name: 'Jupiter Perpetuals Liquidity Provider Token', id: 'jupiter-perpetuals-liquidity-provider-token', type: 'crypto', marketCap: 2355095487 },
  { symbol: 'ARB', name: 'Arbitrum', id: 'arbitrum', type: 'crypto', marketCap: 2332968040 },
  { symbol: 'PUMP', name: 'Pump.fun', id: 'pump-fun', type: 'crypto', marketCap: 2332780934 },
  { symbol: 'SUSDS', name: 'sUSDS', id: 'susds', type: 'crypto', marketCap: 2256803980 },
  { symbol: 'PI', name: 'Pi Network', id: 'pi-network', type: 'crypto', marketCap: 2139048648 },
  { symbol: 'KCS', name: 'KuCoin', id: 'kucoin-shares', type: 'crypto', marketCap: 2062586972 },
  { symbol: 'KAS', name: 'Kaspa', id: 'kaspa', type: 'crypto', marketCap: 2023144681 },
  { symbol: 'GT', name: 'Gate', id: 'gatechain-token', type: 'crypto', marketCap: 2020895879 },
  { symbol: 'RETH', name: 'Rocket Pool ETH', id: 'rocket-pool-eth', type: 'crypto', marketCap: 2007840958 },
  { symbol: 'VET', name: 'VeChain', id: 'vechain', type: 'crypto', marketCap: 1967399445 },
  { symbol: 'ATOM', name: 'Cosmos Hub', id: 'cosmos', type: 'crypto', marketCap: 1943785756 },
  { symbol: 'ALGO', name: 'Algorand', id: 'algorand', type: 'crypto', marketCap: 1930677922 },
  { symbol: 'KHYPE', name: 'Kinetiq Staked HYPE', id: 'kinetic-staked-hype', type: 'crypto', marketCap: 1907831446 },
  { symbol: 'PENGU', name: 'Pudgy Penguins', id: 'pudgy-penguins', type: 'crypto', marketCap: 1895518489 },
  { symbol: 'RSETH', name: 'Kelp DAO Restaked ETH', id: 'kelp-dao-restaked-eth', type: 'crypto', marketCap: 1874410523 },
  { symbol: 'HASH', name: 'Provenance Blockchain', id: 'hash-2', type: 'crypto', marketCap: 1863519724 },
  { symbol: 'FLR', name: 'Flare', id: 'flare-networks', type: 'crypto', marketCap: 1834062564 },
  { symbol: 'USDTB', name: 'USDtb', id: 'usdtb', type: 'crypto', marketCap: 1828426476 },
  { symbol: 'RENDER', name: 'Render', id: 'render-token', type: 'crypto', marketCap: 1800191994 },
  { symbol: 'SEI', name: 'Sei', id: 'sei-network', type: 'crypto', marketCap: 1762728421 },
  { symbol: '2Z', name: 'DoubleZero', id: 'doublezero', type: 'crypto', marketCap: 1740370014 },
  { symbol: 'USDF', name: 'Falcon USD', id: 'falcon-finance', type: 'crypto', marketCap: 1725724513 },
  { symbol: 'BFUSD', name: 'BFUSD', id: 'bfusd', type: 'crypto', marketCap: 1699463523 },
  { symbol: 'OSETH', name: 'StakeWise Staked ETH', id: 'stakewise-v3-oseth', type: 'crypto', marketCap: 1694422429 },
  { symbol: 'LSETH', name: 'Liquid Staked ETH', id: 'liquid-staked-ethereum', type: 'crypto', marketCap: 1612421556 },
  { symbol: 'FIL', name: 'Filecoin', id: 'filecoin', type: 'crypto', marketCap: 1596890121 },
  { symbol: 'SKY', name: 'Sky', id: 'sky', type: 'crypto', marketCap: 1568365171 },
  { symbol: 'TRUMP', name: 'Official Trump', id: 'official-trump', type: 'crypto', marketCap: 1543897991 },
  { symbol: 'FET', name: 'Artificial Superintelligence Alliance', id: 'fetch-ai', type: 'crypto', marketCap: 1539859769 },
  { symbol: 'BONK', name: 'Bonk', id: 'bonk', type: 'crypto', marketCap: 1537283497 },
  { symbol: 'XPL', name: 'Plasma', id: 'plasma', type: 'crypto', marketCap: 1526527309 },
  { symbol: 'LBTC', name: 'Lombard Staked BTC', id: 'lombard-staked-btc', type: 'crypto', marketCap: 1500428598 },
  { symbol: 'QNT', name: 'Quant', id: 'quant-network', type: 'crypto', marketCap: 1495002222 },
  { symbol: 'XAUT', name: 'Tether Gold', id: 'tether-gold', type: 'crypto', marketCap: 1463262008 },
  { symbol: 'IMX', name: 'Immutable', id: 'immutable-x', type: 'crypto', marketCap: 1460380038 },
  { symbol: 'WBNB', name: 'Wrapped BNB', id: 'wbnb', type: 'crypto', marketCap: 1455426063 },
  { symbol: 'EZETH', name: 'Renzo Restaked ETH', id: 'renzo-restaked-eth', type: 'crypto', marketCap: 1455191991 },
  { symbol: 'JUP', name: 'Jupiter', id: 'jupiter-exchange-solana', type: 'crypto', marketCap: 1432651792 },
  { symbol: 'SPX', name: 'SPX6900', id: 'spx6900', type: 'crypto', marketCap: 1324655986 },
  { symbol: 'XDC', name: 'XDC Network', id: 'xdce-crowd-sale', type: 'crypto', marketCap: 1319393908 },
  { symbol: 'OP', name: 'Optimism', id: 'optimism', type: 'crypto', marketCap: 1284956657 },
  { symbol: 'NEXO', name: 'NEXO', id: 'nexo', type: 'crypto', marketCap: 1266330028 },
  { symbol: 'INJ', name: 'Injective', id: 'injective-protocol', type: 'crypto', marketCap: 1222761693 },
  { symbol: 'TIA', name: 'Celestia', id: 'celestia', type: 'crypto', marketCap: 1219833062 },
  { symbol: 'SOLVBTC', name: 'Solv Protocol BTC', id: 'solv-btc', type: 'crypto', marketCap: 1215708260 },
  { symbol: 'CAKE', name: 'PancakeSwap', id: 'pancakeswap-token', type: 'crypto', marketCap: 1188752061 },
  { symbol: 'JUPSOL', name: 'Jupiter Staked SOL', id: 'jupiter-staked-sol', type: 'crypto', marketCap: 1169532539 },
  { symbol: 'PAXG', name: 'PAX Gold', id: 'pax-gold', type: 'crypto', marketCap: 1165034347 },
  { symbol: 'METH', name: 'Mantle Staked Ether', id: 'mantle-staked-ether', type: 'crypto', marketCap: 1148227107 },
  { symbol: 'USDC', name: 'Binance Bridged USDC (BNB Smart Chain)', id: 'binance-bridged-usdc-bnb-smart-chain', type: 'crypto', marketCap: 1138689292 },
  { symbol: 'SYRUPUSDC', name: 'Syrup USDC', id: 'syrupusdc', type: 'crypto', marketCap: 1136860149 },
  { symbol: 'MYX', name: 'MYX Finance', id: 'myx-finance', type: 'crypto', marketCap: 1089727565 },
  { symbol: 'CRV', name: 'Curve DAO', id: 'curve-dao-token', type: 'crypto', marketCap: 1085641344 },
  { symbol: 'STX', name: 'Stacks', id: 'blockstack', type: 'crypto', marketCap: 1080137633 },
  { symbol: 'FDUSD', name: 'First Digital USD', id: 'first-digital-usd', type: 'crypto', marketCap: 1078346828 },
  { symbol: 'LDO', name: 'Lido DAO', id: 'lido-dao', type: 'crypto', marketCap: 1073093344 },
  { symbol: 'S', name: 'Sonic', id: 'sonic-3', type: 'crypto', marketCap: 1039027873 },
  { symbol: 'MSOL', name: 'Marinade Staked SOL', id: 'msol', type: 'crypto', marketCap: 1019669782 },
  { symbol: 'AERO', name: 'Aerodrome Finance', id: 'aerodrome-finance', type: 'crypto', marketCap: 1012565843 },
  { symbol: 'WBTC', name: 'Arbitrum Bridged WBTC (Arbitrum One)', id: 'arbitrum-bridged-wbtc-arbitrum-one', type: 'crypto', marketCap: 993558250 },
  { symbol: 'FLOKI', name: 'FLOKI', id: 'floki', type: 'crypto', marketCap: 989426898 },
  { symbol: 'CLBTC', name: 'clBTC', id: 'clbtc', type: 'crypto', marketCap: 948760030 },
  { symbol: 'ETHFI', name: 'Ether.fi', id: 'ether-fi', type: 'crypto', marketCap: 934456916 },
  { symbol: 'PYTH', name: 'Pyth Network', id: 'pyth-network', type: 'crypto', marketCap: 883554856 },
  { symbol: 'KAIA', name: 'Kaia', id: 'kaia', type: 'crypto', marketCap: 882833712 },
  { symbol: 'GRT', name: 'The Graph', id: 'the-graph', type: 'crypto', marketCap: 875547641 },
  { symbol: 'FTN', name: 'Fasttoken', id: 'fasttoken', type: 'crypto', marketCap: 873638212 },
  { symbol: 'CGETH.HASHKEY', name: 'cgETH Hashkey Cloud', id: 'cgeth-hashkey-cloud', type: 'crypto', marketCap: 865669729 },
  { symbol: 'PENDLE', name: 'Pendle', id: 'pendle', type: 'crypto', marketCap: 802377328 },
  { symbol: 'RLUSD', name: 'Ripple USD', id: 'ripple-usd', type: 'crypto', marketCap: 789652203 },
  { symbol: 'WETH', name: 'L2 Standard Bridged WETH (Base)', id: 'l2-standard-bridged-weth-base', type: 'crypto', marketCap: 779288557 },
  { symbol: 'TBTC', name: 'tBTC', id: 'tbtc', type: 'crypto', marketCap: 770796424 },
  { symbol: 'RAY', name: 'Raydium', id: 'raydium', type: 'crypto', marketCap: 765271095 },
  { symbol: 'IOTA', name: 'IOTA', id: 'iota', type: 'crypto', marketCap: 757277514 },
  { symbol: 'WIF', name: 'dogwifhat', id: 'dogwifcoin', type: 'crypto', marketCap: 749014295 },
  { symbol: 'OUSG', name: 'OUSG', id: 'ousg', type: 'crypto', marketCap: 744498968 },
  { symbol: 'CFX', name: 'Conflux', id: 'conflux-token', type: 'crypto', marketCap: 744470649 },
  { symbol: 'EIGEN', name: 'EigenCloud (prev. EigenLayer)', id: 'eigenlayer', type: 'crypto', marketCap: 742804580 },
  { symbol: 'XTZ', name: 'Tezos', id: 'tezos', type: 'crypto', marketCap: 738163365 },
  { symbol: 'THETA', name: 'Theta Network', id: 'theta-token', type: 'crypto', marketCap: 726820526 },
  { symbol: 'GALA', name: 'GALA', id: 'gala', type: 'crypto', marketCap: 726746816 },
  { symbol: 'VIRTUAL', name: 'Virtuals Protocol', id: 'virtual-protocol', type: 'crypto', marketCap: 722527576 },
  { symbol: 'DEXE', name: 'DeXe', id: 'dexe', type: 'crypto', marketCap: 711023530 },
  { symbol: 'ENS', name: 'Ethereum Name Service', id: 'ethereum-name-service', type: 'crypto', marketCap: 703455665 },
  { symbol: 'USDG', name: 'Global Dollar', id: 'global-dollar', type: 'crypto', marketCap: 700067061 },
  { symbol: 'ETHX', name: 'Stader ETHx', id: 'stader-ethx', type: 'crypto', marketCap: 694255597 },
  { symbol: 'GTETH', name: 'GTETH', id: 'gteth', type: 'crypto', marketCap: 689257386 },
  { symbol: 'USDX', name: 'Stables Labs USDX', id: 'usdx-money-usdx', type: 'crypto', marketCap: 681254336 },
  { symbol: 'SAROS', name: 'Saros', id: 'saros-finance', type: 'crypto', marketCap: 679770625 },
  { symbol: 'SAND', name: 'The Sandbox', id: 'the-sandbox', type: 'crypto', marketCap: 677882583 },
  { symbol: 'USDY', name: 'Ondo US Dollar Yield', id: 'ondo-us-dollar-yield', type: 'crypto', marketCap: 675105023 },
  { symbol: 'AB', name: 'AB', id: 'newton-project', type: 'crypto', marketCap: 670378849 },
  { symbol: 'USTB', name: 'Superstate Short Duration U.S. Government Securities Fund (USTB)', id: 'superstate-short-duration-us-government-securities-fund-ustb', type: 'crypto', marketCap: 654694426 },
  { symbol: 'MANA', name: 'Decentraland', id: 'decentraland', type: 'crypto', marketCap: 647682651 },
  { symbol: 'FARTCOIN', name: 'Fartcoin', id: 'fartcoin', type: 'crypto', marketCap: 645884173 },
  { symbol: 'WETH', name: 'Arbitrum Bridged WETH (Arbitrum One)', id: 'arbitrum-bridged-weth-arbitrum-one', type: 'crypto', marketCap: 644986603 },
  { symbol: 'ATH', name: 'Aethir', id: 'aethir', type: 'crypto', marketCap: 642514972 },
  { symbol: 'DOGE', name: 'Binance-Peg Dogecoin', id: 'binance-peg-dogecoin', type: 'crypto', marketCap: 642492443 },
  { symbol: 'A', name: 'Vaulta', id: 'vaulta', type: 'crypto', marketCap: 640405855 },
  { symbol: 'MORPHO', name: 'Morpho', id: 'morpho', type: 'crypto', marketCap: 635522469 },
  { symbol: 'STRK', name: 'Starknet', id: 'starknet', type: 'crypto', marketCap: 634423600 },
  { symbol: 'JASMY', name: 'JasmyCoin', id: 'jasmycoin', type: 'crypto', marketCap: 624827854 },
  { symbol: '0G', name: '0G', id: 'zero-gravity', type: 'crypto', marketCap: 620258048 },
  { symbol: 'CMETH', name: 'Mantle Restaked ETH', id: 'mantle-restaked-eth', type: 'crypto', marketCap: 620151949 },
  { symbol: 'JTO', name: 'Jito', id: 'jito-governance-token', type: 'crypto', marketCap: 613576044 },
  { symbol: 'BDX', name: 'Beldex', id: 'beldex', type: 'crypto', marketCap: 610470682 },
  { symbol: 'TWT', name: 'Trust Wallet', id: 'trust-wallet-token', type: 'crypto', marketCap: 598924443 },
  { symbol: 'CBETH', name: 'Coinbase Wrapped Staked ETH', id: 'coinbase-wrapped-staked-eth', type: 'crypto', marketCap: 597706697 },
  { symbol: 'SWETH', name: 'Swell Ethereum', id: 'sweth', type: 'crypto', marketCap: 597548155 },
  { symbol: 'WAL', name: 'Walrus', id: 'walrus-2', type: 'crypto', marketCap: 597544264 },
  { symbol: 'FLOW', name: 'Flow', id: 'flow', type: 'crypto', marketCap: 596488396 },
  { symbol: 'BTT', name: 'BitTorrent', id: 'bittorrent', type: 'crypto', marketCap: 593676175 },
  { symbol: 'SN116', name: 'SolMev', id: 'solmev', type: 'crypto', marketCap: 588249695 },
  { symbol: 'BORG', name: 'SwissBorg', id: 'swissborg', type: 'crypto', marketCap: 585392151 },
  { symbol: 'BTC.B', name: 'Avalanche Bridged BTC (Avalanche)', id: 'bitcoin-avalanche-bridged-btc-b', type: 'crypto', marketCap: 561632946 },
  { symbol: 'USD0', name: 'Usual USD', id: 'usual-usd', type: 'crypto', marketCap: 557399068 },
  { symbol: 'WEETH', name: 'Arbitrum Bridged Wrapped eETH (Arbitrum)', id: 'arbitrum-bridged-wrapped-eeth', type: 'crypto', marketCap: 555432439 },
  { symbol: 'BSV', name: 'Bitcoin SV', id: 'bitcoin-cash-sv', type: 'crypto', marketCap: 545515663 },
  { symbol: 'W', name: 'Wormhole', id: 'wormhole', type: 'crypto', marketCap: 542651502 },
  { symbol: 'VKHYPE', name: 'Kinetiq Earn Vault', id: 'kinetiq-earn-vault', type: 'crypto', marketCap: 542341030 },
  { symbol: 'USDAI', name: 'USDai', id: 'usdai', type: 'crypto', marketCap: 531771119 },
  { symbol: 'SAVAX', name: 'BENQI Liquid Staked AVAX', id: 'benqi-liquid-staked-avax', type: 'crypto', marketCap: 527961371 },
  { symbol: 'APE', name: 'ApeCoin', id: 'apecoin', type: 'crypto', marketCap: 510912701 },
  { symbol: 'USDT', name: 'Mantle Bridged USDT (Mantle)', id: 'mantle-bridged-usdt-mantle', type: 'crypto', marketCap: 505526653 },
  { symbol: 'EETH', name: 'ether.fi Staked ETH', id: 'ether-fi-staked-eth', type: 'crypto', marketCap: 504642265 },
  { symbol: 'WAVAX', name: 'Wrapped AVAX', id: 'wrapped-avax', type: 'crypto', marketCap: 504249030 },
  { symbol: 'WHYPE', name: 'Wrapped HYPE', id: 'wrapped-hype', type: 'crypto', marketCap: 501884101 },
  { symbol: 'BBSOL', name: 'Bybit Staked SOL', id: 'bybit-staked-sol', type: 'crypto', marketCap: 499506581 },
  { symbol: 'FLUID', name: 'Fluid', id: 'instadapp', type: 'crypto', marketCap: 494784060 },
  { symbol: 'TUSD', name: 'TrueUSD', id: 'true-usd', type: 'crypto', marketCap: 494243730 },
  { symbol: 'WETH', name: 'Polygon PoS Bridged WETH (Polygon POS)', id: 'polygon-pos-bridged-weth-polygon-pos', type: 'crypto', marketCap: 489853775 },
  { symbol: 'FRXETH', name: 'Frax Ether', id: 'frax-ether', type: 'crypto', marketCap: 488892798 },
  { symbol: 'LION', name: 'Loaded Lions', id: 'loaded-lions', type: 'crypto', marketCap: 488053963 },
  { symbol: 'AIC', name: 'AI Companions', id: 'ai-companions', type: 'crypto', marketCap: 483511891 },
  { symbol: 'DYDX', name: 'dYdX', id: 'dydx-chain', type: 'crypto', marketCap: 482682398 },
  { symbol: 'HNT', name: 'Helium', id: 'helium', type: 'crypto', marketCap: 478422712 },
  { symbol: 'SUN', name: 'Sun Token', id: 'sun-token', type: 'crypto', marketCap: 474542423 },
  { symbol: 'USDD', name: 'USDD', id: 'usdd', type: 'crypto', marketCap: 466509197 },
  { symbol: 'SENA', name: 'Ethena Staked ENA', id: 'ethena-staked-ena', type: 'crypto', marketCap: 461010483 },
  { symbol: 'DAI', name: 'Polygon PoS Bridged DAI (Polygon POS)', id: 'polygon-pos-bridged-dai-polygon-pos', type: 'crypto', marketCap: 458865774 },
  { symbol: 'SYRUP', name: 'Maple Finance', id: 'syrup', type: 'crypto', marketCap: 456167843 },
  { symbol: 'STEAKUSDC', name: 'Steakhouse USDC Morpho Vault', id: 'steakhouse-usdc-morpho-vault', type: 'crypto', marketCap: 453616745 },
  { symbol: 'BRETT', name: 'Brett', id: 'based-brett', type: 'crypto', marketCap: 445428280 },
  { symbol: 'CHZ', name: 'Chiliz', id: 'chiliz', type: 'crypto', marketCap: 442392107 },
  { symbol: 'USDC.E', name: 'Polygon Bridged USDC (Polygon PoS)', id: 'bridged-usdc-polygon-pos-bridge', type: 'crypto', marketCap: 440789693 },
  { symbol: 'DASH', name: 'Dash', id: 'dash', type: 'crypto', marketCap: 436273713 },
  { symbol: 'NEO', name: 'NEO', id: 'neo', type: 'crypto', marketCap: 436205303 },
  { symbol: 'VSN', name: 'Vision', id: 'vision-3', type: 'crypto', marketCap: 434895957 },
  { symbol: 'TEL', name: 'Telcoin', id: 'telcoin', type: 'crypto', marketCap: 433681917 },
  { symbol: 'BEAM', name: 'Beam', id: 'beam-2', type: 'crypto', marketCap: 432229979 },
  { symbol: 'FORM', name: 'Four', id: 'four', type: 'crypto', marketCap: 431881595 },
  { symbol: 'LINEA', name: 'Linea', id: 'linea', type: 'crypto', marketCap: 430084783 },
  { symbol: 'NFT', name: 'APENFT', id: 'apenft', type: 'crypto', marketCap: 429902487 },
  { symbol: 'ASBNB', name: 'Aster Staked BNB', id: 'astherus-staked-bnb', type: 'crypto', marketCap: 426250773 },
  { symbol: 'FF', name: 'Falcon Finance', id: 'falcon-finance-ff', type: 'crypto', marketCap: 418834970 },
  { symbol: 'RUNE', name: 'THORChain', id: 'thorchain', type: 'crypto', marketCap: 414481636 },
  { symbol: 'USYC', name: 'Circle USYC', id: 'hashnote-usyc', type: 'crypto', marketCap: 414158631 },
  { symbol: 'COMP', name: 'Compound', id: 'compound-governance-token', type: 'crypto', marketCap: 412553721 },
  { symbol: 'USDB', name: 'USDB', id: 'usdb', type: 'crypto', marketCap: 407645136 },
  { symbol: 'ETH+', name: 'ETHPlus', id: 'reserve-protocol-eth-plus', type: 'crypto', marketCap: 405394719 },
  { symbol: 'SNX', name: 'Synthetix Network', id: 'havven', type: 'crypto', marketCap: 405269744 },
  { symbol: 'UBTC', name: 'Unit Bitcoin', id: 'unit-bitcoin', type: 'crypto', marketCap: 400205410 },
  { symbol: 'GNO', name: 'Gnosis', id: 'gnosis', type: 'crypto', marketCap: 399642806 },
  { symbol: 'TETH', name: 'Treehouse ETH', id: 'treehouse-eth', type: 'crypto', marketCap: 396674912 },
  { symbol: 'CORE', name: 'Core', id: 'coredaoorg', type: 'crypto', marketCap: 392999306 },
  { symbol: 'DSOL', name: 'Drift Staked SOL', id: 'drift-staked-sol', type: 'crypto', marketCap: 392937914 },
  { symbol: 'ZK', name: 'ZKsync', id: 'zksync', type: 'crypto', marketCap: 392388903 },
  { symbol: 'RSR', name: 'Reserve Rights', id: 'reserve-rights-token', type: 'crypto', marketCap: 389471399 },
  { symbol: 'XCN', name: 'Onyxcoin', id: 'chain-2', type: 'crypto', marketCap: 389111900 },
  { symbol: 'SDAI', name: 'Savings Dai', id: 'savings-dai', type: 'crypto', marketCap: 386494502 },
  { symbol: 'SUPER', name: 'SuperVerse', id: 'superfarm', type: 'crypto', marketCap: 383263449 },
  { symbol: 'ZBCN', name: 'Zebec Network', id: 'zebec-network', type: 'crypto', marketCap: 383242480 },
  { symbol: 'AR', name: 'Arweave', id: 'arweave', type: 'crypto', marketCap: 381213118 },
  { symbol: 'EGLD', name: 'MultiversX', id: 'elrond-erd-2', type: 'crypto', marketCap: 379992030 },
  { symbol: 'XEC', name: 'eCash', id: 'ecash', type: 'crypto', marketCap: 366885822 },
  { symbol: 'AXS', name: 'Axie Infinity', id: 'axie-infinity', type: 'crypto', marketCap: 365675120 },
  { symbol: 'WETH', name: 'Mantle Bridged WETH (Mantle)', id: 'wrapped-ether-mantle-bridge', type: 'crypto', marketCap: 365542032 },
  { symbol: 'USDF', name: 'Aster USDF', id: 'astherus-usdf', type: 'crypto', marketCap: 362651165 },
  { symbol: '1INCH', name: '1INCH', id: '1inch', type: 'crypto', marketCap: 361870695 },
  { symbol: 'OHM', name: 'Olympus', id: 'olympus', type: 'crypto', marketCap: 361411749 },
  { symbol: 'EUTBL', name: 'Spiko EU T-Bills Money Market Fund', id: 'eutbl', type: 'crypto', marketCap: 361219045 },
  { symbol: 'DEEP', name: 'DeepBook', id: 'deep', type: 'crypto', marketCap: 359801904 },
  { symbol: 'BERA', name: 'Berachain', id: 'berachain-bera', type: 'crypto', marketCap: 359315554 },
  { symbol: 'KAVA', name: 'Kava', id: 'kava', type: 'crypto', marketCap: 357836771 },
  { symbol: 'XLM', name: 'Stellar', id: 'stellar', type: 'crypto', marketCap: 12561064160 },
  { symbol: 'WEETH', name: 'Wrapped eETH', id: 'wrapped-eeth', type: 'crypto', marketCap: 11872970362 },
  { symbol: 'BCH', name: 'Bitcoin Cash', id: 'bitcoin-cash', type: 'crypto', marketCap: 11735306606 },
  { symbol: 'WETH', name: 'WETH', id: 'weth', type: 'crypto', marketCap: 10926651499 },
  { symbol: 'LTC', name: 'Litecoin', id: 'litecoin', type: 'crypto', marketCap: 9283425592 },
  { symbol: 'HBAR', name: 'Hedera', id: 'hedera-hashgraph', type: 'crypto', marketCap: 9192403074 },
  { symbol: 'LEO', name: 'LEO Token', id: 'leo-token', type: 'crypto', marketCap: 8878487190 },
  { symbol: 'BSC-USD', name: 'Binance Bridged USDT (BNB Smart Chain)', id: 'binance-bridged-usdt-bnb-smart-chain', type: 'crypto', marketCap: 7989464964 },
  { symbol: 'USDS', name: 'USDS', id: 'usds', type: 'crypto', marketCap: 7957153041 },
  { symbol: 'CBBTC', name: 'Coinbase Wrapped BTC', id: 'coinbase-wrapped-btc', type: 'crypto', marketCap: 7910245911 },
  { symbol: 'SHIB', name: 'Shiba Inu', id: 'shiba-inu', type: 'crypto', marketCap: 7262335346 },
  { symbol: 'CRO', name: 'Cronos', id: 'crypto-com-chain', type: 'crypto', marketCap: 7138858341 },
  { symbol: 'TON', name: 'Toncoin', id: 'the-open-network', type: 'crypto', marketCap: 7054275047 },
  { symbol: 'USDT0', name: 'USDT0', id: 'usdt0', type: 'crypto', marketCap: 6674656722 },
  { symbol: 'DOT', name: 'Polkadot', id: 'polkadot', type: 'crypto', marketCap: 6372057799 },
  { symbol: 'MNT', name: 'Mantle', id: 'mantle', type: 'crypto', marketCap: 6371350524 },
  { symbol: 'WBT', name: 'WhiteBIT Coin', id: 'whitebit', type: 'crypto', marketCap: 6368198265 },
  { symbol: 'XMR', name: 'Monero', id: 'monero', type: 'crypto', marketCap: 6073192571 },
  { symbol: 'SUSDE', name: 'Ethena Staked USDe', id: 'ethena-staked-usde', type: 'crypto', marketCap: 5813350114 },
  { symbol: 'WLFI', name: 'World Liberty Financial', id: 'world-liberty-financial', type: 'crypto', marketCap: 5472466051 },
];

export default top270Cryptos;
