#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Pre-commit Hook Integration - Automated quality gates before commits

.DESCRIPTION
    Integrates enhanced protection into Git workflow:
    1. Runs quality gates before each commit
    2. Enforces test coverage thresholds
    3. Blocks commits with security vulnerabilities
    4. Provides fast feedback for common issues
    5. Progressive quality improvement

.EXAMPLE
    .\setup-precommit-hooks.ps1

.EXAMPLE
    .\setup-precommit-hooks.ps1 -Strict

.NOTES
    This sets up Git hooks to run enhanced protection automatically
#>

param(
    [switch]$Strict,        # Strict mode - block on any quality gate failure
    [switch]$UninstallHooks, # Remove existing hooks
    [int]$CoverageThreshold = 15,  # Minimum coverage to allow commits
    [switch]$CIMode,        # CI/CD mode - output machine-readable JSON
    [switch]$DryRun         # Dry run - preview hook installation without creating files
)

$ErrorActionPreference = 'Continue'

# Import common functions for CI mode
if ($CIMode) {
    $modulePath = Join-Path $PSScriptRoot 'lib\Common-Functions.ps1'
    if (Test-Path $modulePath) {
        Import-Module $modulePath -Force -ErrorAction SilentlyContinue
    }
}

$startTime = Get-Date

# Skip header in CI mode
if (-not $CIMode) {
    Write-Host ''
    Write-Host '🪝 PRE-COMMIT HOOKS SETUP' -ForegroundColor Cyan
    Write-Host '=' * 50 -ForegroundColor Gray
    Write-Host ''

    if ($DryRun) {
        Write-Host '🔍 DRY RUN MODE - Preview hook installation without creating files' -ForegroundColor Yellow
        Write-Host ''
    }
}

# Resolve repository root (actual Git root, not the tools folder)
function Get-GitRoot {
    try {
        $gitPath = git rev-parse --show-toplevel 2>$null
        if ($LASTEXITCODE -eq 0 -and $gitPath) { return $gitPath }
    } catch { }

    # Fallback: walk up from current script directory until .git is found
    $dir = (Resolve-Path (Join-Path $PSScriptRoot '..'))
    while ($dir -and (Test-Path $dir)) {
        if (Test-Path (Join-Path $dir '.git')) { return $dir }
        $parent = Split-Path $dir -Parent
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return (Resolve-Path (Join-Path $PSScriptRoot '..\..'))
}

$repoRoot = Get-GitRoot
$gitHooksDir = Join-Path $repoRoot '.git/hooks'

# Ensure hooks directory exists
if (-not (Test-Path $gitHooksDir)) {
    New-Item -ItemType Directory -Force -Path $gitHooksDir | Out-Null
}

# ============================================
# UNINSTALL EXISTING HOOKS
# ============================================
if ($UninstallHooks) {
    Write-Host '🗑️  Removing existing hooks...' -ForegroundColor Yellow

    $hookFiles = @('pre-commit', 'pre-push', 'commit-msg')

    foreach ($hook in $hookFiles) {
        $hookPath = Join-Path $gitHooksDir $hook
        if (Test-Path $hookPath) {
            Remove-Item $hookPath -Force
            Write-Host "   ✅ Removed $hook hook" -ForegroundColor Green
        }
    }

    Write-Host ''
    Write-Host '🎉 All hooks removed successfully!' -ForegroundColor Green
    return
}

# ============================================
# CREATE PRE-COMMIT HOOK
# ============================================
Write-Host '🔧 Creating pre-commit hook...' -ForegroundColor Yellow

$enforceStrictParam = if ($Strict) { '-EnforceStrict' } else { '' }
$preCommitCoverage = [int]$CoverageThreshold

$preCommitHook = @"
#!/bin/sh
# Enhanced Pre-commit Hook
# Runs quality gates before allowing commits
# Generated by: setup-precommit-hooks.ps1

echo ""
echo "🛡️  Running pre-commit quality gates..."
echo ""

# Check if we're on Windows and use PowerShell
if command -v pwsh >/dev/null 2>&1; then
    SHELL_CMD="pwsh"
elif command -v powershell >/dev/null 2>&1; then
    SHELL_CMD="powershell"
else
    echo "❌ PowerShell not found. Please install PowerShell Core or Windows PowerShell."
    exit 1
fi

# Get the repository root
REPO_ROOT=`$(git rev-parse --show-toplevel)`
PROTECTION_SCRIPT="`$REPO_ROOT/tools/test-runner.ps1"
SECURITY_SCRIPT="`$REPO_ROOT/tools/security-scanner.ps1"

# Run fast quality checks (lint, format, typecheck) for pre-commit
if [ -f "`$PROTECTION_SCRIPT" ]; then
    echo "🔍 Running fast quality checks..."

    if `$SHELL_CMD -ExecutionPolicy Bypass -File "`$PROTECTION_SCRIPT" -FastCheck $enforceStrictParam; then
        echo ""
        echo "✅ Quality gates passed!"
        echo ""

        # Run security scan (quick mode for pre-commit)
        if [ -f "`$SECURITY_SCRIPT" ]; then
            echo "🔒 Running security scan..."

            if `$SHELL_CMD -ExecutionPolicy Bypass -File "`$SECURITY_SCRIPT" -Quick -CIMode; then
                echo ""
                echo "✅ Security scan passed! Commit allowed."
                echo ""
                exit 0
            else
                echo ""
                echo "⚠️  Security issues detected!"
                echo ""
                echo "🔧 To review issues:"
                echo "   • Run: .\tools\security-scanner.ps1 -Deep"
                echo "   • Review security report and fix issues"
                echo "   • Or use: git commit --no-verify (skip hooks - use carefully!)"
                echo ""
                exit 1
            fi
        else
            echo "⚠️  Security scanner not found. Skipping security scan."
            echo "✅ Commit allowed."
            echo ""
            exit 0
        fi
    else
        echo ""
        echo "❌ Quality gates failed!"
        echo ""
        echo "🔧 To fix issues:"
        echo "   • Run: .\tools\test-runner.ps1 -GenerateReport"
        echo "   • Review failed gates and fix issues"
        echo "   • Or use: git commit --no-verify (skip hooks - use carefully!)"
        echo ""
        exit 1
    fi
else
    echo "⚠️  Enhanced protection script not found. Running basic validation..."

    # Fallback to basic lokifi validation
    if [ -f "`$LOKIFI_SCRIPT" ]; then
        if `$SHELL_CMD -ExecutionPolicy Bypass -File "`$LOKIFI_SCRIPT" validate -Quick; then
            echo "✅ Basic validation passed!"
            exit 0
        else
            echo "❌ Basic validation failed!"
            exit 1
        fi
    else
        echo "⚠️  No validation scripts found. Allowing commit."
        exit 0
    fi
fi
"@

$preCommitPath = Join-Path $gitHooksDir 'pre-commit'

if ($DryRun) {
    Write-Host "   🔍 Would create: $preCommitPath" -ForegroundColor Yellow
    Write-Host "      Content: $($preCommitHook.Length) characters" -ForegroundColor Gray
} else {
    $preCommitHook | Out-File -FilePath $preCommitPath -Encoding UTF8 -NoNewline

    # Make hook executable (Windows - no chmod needed, but set for cross-platform)
    try {
        if (Get-Command 'chmod' -ErrorAction SilentlyContinue) {
            & chmod +x $preCommitPath
        }
    } catch {
        # Ignore chmod errors on Windows
    }

    Write-Host '   ✅ Created pre-commit hook' -ForegroundColor Green
}

# ============================================
# CREATE PRE-PUSH HOOK
# ============================================
Write-Host '🔧 Creating pre-push hook...' -ForegroundColor Yellow

$prePushCoverage = [int]$CoverageThreshold + 5

$prePushHook = @"
#!/bin/sh
# Enhanced Pre-push Hook
# Runs comprehensive tests before pushing to remote
# Generated by: setup-precommit-hooks.ps1

echo ""
echo "🚀 Running pre-push comprehensive checks..."
echo ""

# Check for PowerShell
if command -v pwsh >/dev/null 2>&1; then
    SHELL_CMD="pwsh"
elif command -v powershell >/dev/null 2>&1; then
    SHELL_CMD="powershell"
else
    echo "❌ PowerShell not found."
    exit 1
fi

REPO_ROOT=`$(git rev-parse --show-toplevel)`
PROTECTION_SCRIPT="`$REPO_ROOT/tools/test-runner.ps1"

# Run comprehensive protection checks
if [ -f "`$PROTECTION_SCRIPT" ]; then
    echo "🔍 Running comprehensive protection analysis..."

    # Use higher coverage threshold for push
    PUSH_COVERAGE=$prePushCoverage

    if `$SHELL_CMD -ExecutionPolicy Bypass -File "`$PROTECTION_SCRIPT" -PreCommit -CoverageThreshold `$PUSH_COVERAGE -Quiet; then
        echo ""
        echo "✅ All comprehensive checks passed! Push allowed."
        echo ""
        exit 0
    else
        echo ""
        echo "❌ Comprehensive checks failed!"
        echo ""
        echo "🔧 Before pushing:"
        echo "   • Fix quality gate failures"
        echo "   • Increase test coverage to `$PUSH_COVERAGE%+"
        echo "   • Resolve security vulnerabilities"
        echo "   • Or use: git push --no-verify (skip hooks - use very carefully!)"
        echo ""
        exit 1
    fi
else
    echo "⚠️  Enhanced protection not found. Allowing push."
    exit 0
fi
"@

$prePushPath = Join-Path $gitHooksDir 'pre-push'

if ($DryRun) {
    Write-Host "   🔍 Would create: $prePushPath" -ForegroundColor Yellow
} else {
    $prePushHook | Out-File -FilePath $prePushPath -Encoding UTF8 -NoNewline
}

try {
    if (Get-Command 'chmod' -ErrorAction SilentlyContinue) {
        & chmod +x $prePushPath
    }
} catch {
    # Ignore chmod errors
}

Write-Host '   ✅ Created pre-push hook' -ForegroundColor Green

# ============================================
# CREATE COMMIT-MSG HOOK
# ============================================
Write-Host '🔧 Creating commit-msg hook...' -ForegroundColor Yellow

$commitMsgHook = @"
#!/bin/sh
# Enhanced Commit Message Hook
# Enforces conventional commit format and quality
# Generated by: setup-precommit-hooks.ps1

COMMIT_MSG_FILE=`$1
COMMIT_MSG=`$(cat `$COMMIT_MSG_FILE`)

echo "📝 Validating commit message format..."

# Check for conventional commit format
if echo "`$COMMIT_MSG" | grep -qE '^(feat|fix|docs|style|refactor|test|chore|perf|build|ci|revert)(\(.+\))?: .{1,50}'; then
    echo "✅ Commit message format is valid"

    # Check for minimum description length
    if [ `${#COMMIT_MSG} -lt 10 ]; then
        echo "❌ Commit message too short (minimum 10 characters)"
        echo ""
        echo "📋 Good commit message format:"
        echo "   feat: add user authentication system"
        echo "   fix: resolve login form validation issue"
        echo "   docs: update API documentation"
        echo ""
        exit 1
    fi

    # Check for prohibited words
    if echo "`$COMMIT_MSG" | grep -qi 'WIP\|TODO\|FIXME\|HACK\|XXX'; then
        echo "⚠️  Warning: Commit contains work-in-progress markers"
        echo "   Consider completing the work before committing"
        echo ""
        # Don't block, just warn
    fi

    exit 0
else
    echo "❌ Invalid commit message format!"
    echo ""
    echo "📋 Use conventional commit format:"
    echo "   <type>[optional scope]: <description>"
    echo ""
    echo "   Types: feat, fix, docs, style, refactor, test, chore, perf, build, ci, revert"
    echo ""
    echo "   Examples:"
    echo "   ✅ feat: add crypto price alerts"
    echo "   ✅ fix(auth): resolve JWT token expiration"
    echo "   ✅ docs: update installation instructions"
    echo "   ✅ test: add unit tests for trading logic"
    echo ""
    echo "   Current message: `$COMMIT_MSG"
    echo ""
    exit 1
fi
"@

$commitMsgPath = Join-Path $gitHooksDir 'commit-msg'

if ($DryRun) {
    Write-Host "   🔍 Would create: $commitMsgPath" -ForegroundColor Yellow
} else {
    $commitMsgHook | Out-File -FilePath $commitMsgPath -Encoding UTF8 -NoNewline
}

try {
    if (Get-Command 'chmod' -ErrorAction SilentlyContinue) {
        & chmod +x $commitMsgPath
    }
} catch {
    # Ignore chmod errors
}

Write-Host '   ✅ Created commit-msg hook' -ForegroundColor Green

# ============================================
# CREATE HOOK BYPASS SCRIPT
# ============================================
Write-Host '🔧 Creating hook bypass utility...' -ForegroundColor Yellow

$bypassScript = @"
#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Emergency hook bypass utility

.DESCRIPTION
    Allows bypassing Git hooks in emergency situations.
    Use very carefully - bypasses all quality gates!

.EXAMPLE
    .\bypass-hooks.ps1 -Commit "emergency fix"

.EXAMPLE
    .\bypass-hooks.ps1 -Push
#>

param(
    [string]`$Commit,
    [switch]`$Push,
    [string]`$Message = "Emergency bypass - review needed"
)

Write-Host ""
Write-Host "🚨 EMERGENCY HOOK BYPASS" -ForegroundColor Red
Write-Host "=" * 40 -ForegroundColor Yellow
Write-Host ""

if (`$Commit) {
    Write-Host "⚠️  Bypassing pre-commit hooks..." -ForegroundColor Yellow
    Write-Host "   Reason: `$Message" -ForegroundColor Gray
    Write-Host ""

    git commit -m "`$Commit" --no-verify

    if (`$LASTEXITCODE -eq 0) {
        Write-Host "✅ Emergency commit successful" -ForegroundColor Green
        Write-Host "🔍 IMPORTANT: Review this commit ASAP and fix any issues!" -ForegroundColor Red
    } else {
        Write-Host "❌ Emergency commit failed" -ForegroundColor Red
    }
}

if (`$Push) {
    Write-Host "⚠️  Bypassing pre-push hooks..." -ForegroundColor Yellow
    Write-Host "   Reason: `$Message" -ForegroundColor Gray
    Write-Host ""

    git push --no-verify

    if (`$LASTEXITCODE -eq 0) {
        Write-Host "✅ Emergency push successful" -ForegroundColor Green
        Write-Host "🔍 IMPORTANT: Monitor CI/CD pipeline for failures!" -ForegroundColor Red
    } else {
        Write-Host "❌ Emergency push failed" -ForegroundColor Red
    }
}

if (-not `$Commit -and -not `$Push) {
    Write-Host "📋 Usage Examples:" -ForegroundColor Cyan
    Write-Host "   .\bypass-hooks.ps1 -Commit 'hotfix: critical security patch'" -ForegroundColor Gray
    Write-Host "   .\bypass-hooks.ps1 -Push -Message 'production emergency'" -ForegroundColor Gray
    Write-Host ""
    Write-Host "⚠️  Only use in genuine emergencies!" -ForegroundColor Yellow
}

Write-Host ""
"@

$bypassPath = Join-Path $PSScriptRoot 'bypass-hooks.ps1'
$bypassScript | Out-File -FilePath $bypassPath -Encoding UTF8

Write-Host '   ✅ Created bypass utility: bypass-hooks.ps1' -ForegroundColor Green

# ============================================
# TEST HOOKS
# ============================================
Write-Host ''
Write-Host '🧪 Testing hook installation...' -ForegroundColor Yellow

$testPassed = 0
$totalTests = 3

# Test pre-commit hook
if (Test-Path $preCommitPath) {
    Write-Host '   ✅ pre-commit hook installed' -ForegroundColor Green
    $testPassed++
} else {
    Write-Host '   ❌ pre-commit hook missing' -ForegroundColor Red
}

# Test pre-push hook
if (Test-Path $prePushPath) {
    Write-Host '   ✅ pre-push hook installed' -ForegroundColor Green
    $testPassed++
} else {
    Write-Host '   ❌ pre-push hook missing' -ForegroundColor Red
}

# Test commit-msg hook
if (Test-Path $commitMsgPath) {
    Write-Host '   ✅ commit-msg hook installed' -ForegroundColor Green
    $testPassed++
} else {
    Write-Host '   ❌ commit-msg hook missing' -ForegroundColor Red
}

# ============================================
# SUMMARY
# ============================================
Write-Host ''
Write-Host '=' * 50 -ForegroundColor Gray
Write-Host ''
Write-Host '🎯 HOOK SETUP SUMMARY' -ForegroundColor Cyan
Write-Host ''

Write-Host "   📊 Installation: $testPassed/$totalTests hooks installed" -ForegroundColor $(if ($testPassed -eq $totalTests) { 'Green' } else { 'Red' })
Write-Host "   🔒 Mode: $(if ($Strict) { 'Strict (blocks on any failure)' } else { 'Relaxed (warnings for minor issues)' })" -ForegroundColor $(if ($Strict) { 'Red' } else { 'Yellow' })
Write-Host "   📈 Coverage Threshold: $CoverageThreshold%" -ForegroundColor Gray
Write-Host ''

Write-Host '🪝 Installed Hooks:' -ForegroundColor Yellow
Write-Host '   🔍 pre-commit: Quality gates before each commit' -ForegroundColor Gray
Write-Host '   🚀 pre-push: Comprehensive checks before push' -ForegroundColor Gray
Write-Host '   📝 commit-msg: Enforces conventional commit format' -ForegroundColor Gray
Write-Host ''

Write-Host '🎯 What Happens Now:' -ForegroundColor Cyan
Write-Host ''
Write-Host '   Every commit will:' -ForegroundColor White
Write-Host '     • Run quality gates (maintainability, security, complexity)' -ForegroundColor Gray
Write-Host "     • Check test coverage (minimum $CoverageThreshold%)" -ForegroundColor Gray
Write-Host '     • Scan for security vulnerabilities' -ForegroundColor Gray
Write-Host '     • Validate commit message format' -ForegroundColor Gray
Write-Host ''
Write-Host '   Every push will:' -ForegroundColor White
Write-Host '     • Run comprehensive protection analysis' -ForegroundColor Gray
Write-Host "     • Require higher coverage threshold ($($CoverageThreshold + 5)%)" -ForegroundColor Gray
Write-Host '     • Execute test suite' -ForegroundColor Gray
Write-Host '     • Generate protection report' -ForegroundColor Gray
Write-Host ''

if ($testPassed -eq $totalTests) {
    Write-Host '🎉 All hooks installed successfully!' -ForegroundColor Green
    Write-Host ''
    Write-Host '🔧 Test your setup:' -ForegroundColor Cyan
    Write-Host '   1. Make a small change to a file' -ForegroundColor Gray
    Write-Host "   2. Run: git add . && git commit -m 'test: verify hooks working'" -ForegroundColor Gray
    Write-Host '   3. Watch the quality gates run automatically!' -ForegroundColor Gray
    Write-Host ''
    Write-Host '🚨 Emergency Commands:' -ForegroundColor Yellow
    Write-Host "   .\tools\bypass-hooks.ps1 -Commit 'emergency: critical fix'  # Skip all hooks" -ForegroundColor Gray
    Write-Host '   git commit --no-verify                                       # Skip pre-commit' -ForegroundColor Gray
    Write-Host '   git push --no-verify                                         # Skip pre-push' -ForegroundColor Gray
} else {
    Write-Host '⚠️  Some hooks failed to install. Check file permissions.' -ForegroundColor Yellow
}

# CI/CD mode output
if ($CIMode) {
    $endTime = Get-Date
    $duration = ($endTime - $startTime).TotalMilliseconds

    $success = ($testPassed -eq $totalTests)
    $warnings = @()
    $errors = @()

    if (-not $success) {
        $errors += "$($totalTests - $testPassed) hook(s) failed to install"
    }

    $results = @{
        hooks_installed    = $testPassed
        hooks_total        = $totalTests
        strict_mode        = $Strict.IsPresent
        coverage_threshold = $CoverageThreshold
        uninstalled        = $UninstallHooks.IsPresent
    }

    $output = New-CIModeOutput `
        -ToolName 'setup-precommit-hooks' `
        -Success $success `
        -Results $results `
        -Errors $errors `
        -Warnings $warnings

    $output.duration_ms = [math]::Round($duration, 2)
    $output | ConvertTo-Json -Depth 10 | Write-Host

    exit $output.exit_code
}

Write-Host ''
Write-Host '📚 Documentation:' -ForegroundColor Cyan
Write-Host '   Test Runner: .\tools\test-runner.ps1 --help' -ForegroundColor Gray
Write-Host '   Codebase Analyzer: .\tools\codebase-analyzer.ps1' -ForegroundColor Gray
Write-Host '   Hook Management: .\tools\setup-precommit-hooks.ps1 -UninstallHooks' -ForegroundColor Gray
Write-Host ''
